# command_cloudbuild.yml
# 作用：配置 RBE（远程构建执行）的命令规则
commands:
  # 本地仅执行的命令（如本地文件预处理、依赖检查）
  local_only:
    - "CXX_COMPILER__LumeShaderCompiler"
    - "CXX_COMPILER__LumeShaderCompiler"
    - "CXX_EXECUTABLE_LINKER__LumeShaderCompiler" 
    - "CXX_COMPILER__SPIRV-Tools-shared"
    - "CXX_SHARED_LIBRARY_LINKER__SPIRV-Tools-shared"
    - "CXX_COMPILER__SPIRV-Tools-static"
    - "CXX_STATIC_LIBRARY_LINKER__SPIRV-Tools-static"
    - "CXX_COMPILER__SPIRV-Tools-opt"
    - "CXX_STATIC_LIBRARY_LINKER__SPIRV-Tools-opt"
    - "CXX_COMPILER__SPIRV-Tools-reduce"
    - "CXX_STATIC_LIBRARY_LINKER__SPIRV-Tools-reduce"
    - "CXX_COMPILER__SPIRV-Tools-link"
    - "CXX_STATIC_LIBRARY_LINKER__SPIRV-Tools-link"
    - "CXX_COMPILER__SPIRV-Tools-lint"
    - "CXX_STATIC_LIBRARY_LINKER__SPIRV-Tools-lint"
    - "CXX_COMPILER__SPIRV-Tools-diff"
    - "CXX_STATIC_LIBRARY_LINKER__SPIRV-Tools-diff"
    - "CXX_COMPILER__GenericCodeGen"
    - "CXX_STATIC_LIBRARY_LINKER__GenericCodeGen"
    - "CXX_COMPILER__MachineIndependent"
    - "CXX_STATIC_LIBRARY_LINKER__MachineIndependent"
    - "CXX_COMPILER__glslang"
    - "CXX_STATIC_LIBRARY_LINKER__glslang"
    - "CXX_COMPILER__OSDependent"
    - "CXX_STATIC_LIBRARY_LINKER__OSDependent"
    - "CXX_COMPILER__OGLCompiler"
    - "CXX_STATIC_LIBRARY_LINKER__OGLCompiler"
    - "CXX_COMPILER__SPIRV"
    - "CXX_STATIC_LIBRARY_LINKER__SPIRV"
    - "CXX_COMPILER__spirv-cross-glsl"
    - "CXX_STATIC_LIBRARY_LINKER__spirv-cross-glsl"
    - "CXX_COMPILER__spirv-cross-core"
    - "CXX_STATIC_LIBRARY_LINKER__spirv-cross-core"
    - "CXX_COMPILER__LumeAssetCompiler"
    - "CXX_EXECUTABLE_LINKER__LumeAssetCompiler"
    - "clang_x64_rust_bin"
    - "clang_x64_rust_macro"
    - "clang_x64_rust_rlib"
    - "rust_bin"
    - "rust_cdylib"
    - "rust_dylib"
    - "rust_rlib"
    - "rust_staticlib"
    - "copy"
  # 远程执行但不缓存的命令（如每次需重新拉取资源的命令）
  remote_no_cache:
  # 模糊匹配的命令（如包含特定关键词的编译命令）
  fuzzy_rule:
    - "build_toolchain_ohos_ohos_clang_arm__rule"
    - "build_toolchain_linux_clang_x64__rule"
    - "build_toolchain_mingw_mingw_x86_64__rule"
    - "solink"
    - "alink"
    - "link"
    - "asm_defines/asm_defines/defines"
    - "soft_musl_crt/crti"
    - "FREETYPE_MINOR"
    - "-DACE_LOG_TAG=\\\"Ace\\\""
    - "compiler/optimizer/code_generator/target"
    - "build/toolchain/rustc_wrapper.py" 
    - "QuickFixService"
    - "BundleTool"
    - "render_service_base/rs_base_blocklist"
    - "render_service_client/rs_client_blocklist"
    - "externals/libjpeg-turbo/libjpeg"
    - "externals/libjpeg-turbo/simd"
    - "touch "

